contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #staramr channel"
    url: https://nfcore.slack.com/channels/staramr
    about: Discussion about the phac-nml/staramrnf pipeline
